apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: monitoring-stack
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: monitoring-stack
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring-stack
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-stack
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: monitoring-stack
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
