apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: monitoring-stack
  labels:
    app: consumer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer-deployment
  template:
    metadata:
      labels:
        app: consumer-deployment
    spec:
      containers:
        - name: consumer-deployment
          image: consumer-deployment:latest
          imagePullPolicy: Never
          env:
            - name: CONFIG_MINIO_URL
              value: "minio-service.monitoring-stack.svc.cluster.local:9000"
            - name: CONFIG_MINIO_ACCESS_KEY
              value: "admin"
            - name: CONFIG_MINIO_SECRET_KEY
              value: "admin"
            - name: CONFIG_MINIO_BUCKET
              value: "intrusiones"
            - name: CONFIG_INFLUX_URL
              value: "influxdb-service.monitoring-stack.svc.cluster.local:8086"
            - name: CONFIG_INFLUX_TOKEN
              value: 'DJX9QsBpBUJkI3V50B40np4OfT_LuYPHvHbPwiD5-gg_mfAJ84rlQ8Zf2swi4Fua60sXXAXskJ0XkGQY1sOxpg=='
            - name: CONFIG_INFLUX_ORG
              value: "miorganizacion"
            - name: CONFIG_INFLUX_BUCKET
              value: "intrusiones"
            - name: CONFIG_RABBITMQ_URL
              value: "rabbitmq-service.monitoring-stack.svc.cluster.local:5672"
            - name: CONFIG_RABBITMQ_USERNAME
              value: "admin"
            - name: CONFIG_RABBITMQ_PASSWORD
              value: "admin"
            - name: CONFIG_RABBITMQ_QUEUE
              value: "images"
