apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-metadata-deployment
  namespace: monitoring-stack
  labels:
    app: consumer-metadata-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer-metadata-deployment
  template:
    metadata:
      labels:
        app: consumer-metadata-deployment
    spec:
      containers:
        - name: consumer-metadata-deployment
          image: adriitoral/viabi-consumer-metadata:latest
          env:
            - name: CONFIG_INFLUX_URL
              value: "influxdb-service.monitoring-stack.svc.cluster.local:8086"
            - name: CONFIG_INFLUX_TOKEN
              value: 'Bg1W8hRrlLW0lsngsHnXQ6KJH-TPdVOP5DpTWSBkGxBxIULGLv_GA157NwdSjmxJ8E-8_2YZ4yvuFcZfnt_mJw=='
            - name: CONFIG_INFLUX_ORG
              value: "miorganizacion"
            - name: CONFIG_INFLUX_BUCKET
              value: "intrusiones"
            - name: CONFIG_RABBITMQ_URL
              value: "rabbitmq-service.monitoring-stack.svc.cluster.local:5672"
            - name: CONFIG_RABBITMQ_USERNAME
              value: "admin"
            - name: CONFIG_RABBITMQ_PASSWORD
              value: "Admin@12345"
            - name: CONFIG_RABBITMQ_QUEUE
              value: "metadata"
