apiVersion: v1
kind: Pod
metadata:
	name: grafana
	namespace: monitoring-stack
	labels:
		app: grafana
spec:
	containers:
		- name: grafana
		  image: grafana/grafana:latest
		  ports:
			  - containerPort: 3000