# nonk8s
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: monitoring-stack
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = admin
  service:
    type: NodePort
