apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: monitoring-stack
  labels:
    app: minio-deployment
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-deployment
  template:
    metadata:
      labels:
        app: minio-deployment
    spec:
      containers:
        - name: minio-deployment
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "admin"
            - name: MINIO_ROOT_PASSWORD
              value: "Admin@12345"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: { }
