apiVersion: v1
kind: Pod
metadata:
	name: influxdb
	namespace: monitoring-stack
	labels:
		app: influxdb
spec:
	containers:
		- name: influxdb
		  image: influxdb:latest
		  ports:
			  - containerPort: 8086
		  env:
			  - name: INFLUXDB_DB
		  value: "metrics"