apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: monitoring-stack
  labels:
    app: influxdb-deployment
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      name: api
  selector:
    app: influxdb-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  namespace: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-deployment
  template:
    metadata:
      labels:
        app: influxdb-deployment
    spec:
      containers:
        - name: influxdb-deployment
          image: influxdb:2.7.1  # Puedes cambiar a la versión que prefieras
          ports:
            - containerPort: 8086
              name: api
          env:
            # Estos parámetros inician el setup automático si la base de datos aún no se ha inicializado
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "miorganizacion"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "mibucket"
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-storage
          emptyDir: { }  # Para entornos de pruebas; en producción usa un PVC para persistencia
