apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: monitoring-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: monitoring-stack
  labels:
    app: influxdb-deployment
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      name: api
  selector:
    app: influxdb-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  namespace: monitoring-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-deployment
  template:
    metadata:
      labels:
        app: influxdb-deployment
    spec:
      containers:
        - name: influxdb-deployment
          image: influxdb:2.7.1
          ports:
            - containerPort: 8086
              name: api
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "Admin@12345"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "miorganizacion"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "mibucket"
            - name: DOCKER_INFLUXDB_INIT_RETENTION
              value: "30d"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: "MiTokenPersonalizado123456789"
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc